---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e .
  yamllint
  ansible-lint

platforms:
  - name: nginx-ubuntu
    box: ubuntu/focal64
    interfaces:
      - auto_config: true
      ip: 192.168.100.5
      netmask: 29
      network_name: private_network
      virtualbox__intnet: true
    groups: testshost
  - name: nginx-debian
    box: debian/buster64
    interfaces:
      - auto_config: true
      ip: 192.168.100.6
      netmask: 29
      network_name: private_network
      virtualbox__intnet: true
    groups: testshost

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
