---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e .
  yamllint .
  ansible-lint

platforms:
  - name: nginx-ubuntu
    box: ubuntu/focal64
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.5
        netmask: 24
        auto_config: true
  - name: nginx-debian
    box: debian/buster64
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.6
        netmask: 24
        auto_config: true
  - name: nginx-debian11
    box: debian/bullseye64
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.7
        netmask: 24
        auto_config: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: ansible
