---

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: (check) Test if services are started and enabled
    systemd:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - nginx.service

  - name: (check) Test if services ports are open and reachable
    shell: "ss -ntlp | grep {{ item }}"
    loop:
      - 80
      - nginx
    changed_when: false

  - name: (check) Test if web interface is OK
    uri:
      url: "http://localhost"
      status_code: 200
